package constants;

public enum DBConstants {
	CUSTOMERS, COMPANIES, COUPONS, CUSTOMERS_VS_COUPONS, ID, FIRST_NAME, LAST_NAME, NAME, EMAIL, PASSWORD, CUSTOMER_ID,
	COUPON_ID, COMPANY_ID, CATEGORY_ID, TITLE, DESCRIPTION, START_DATE, END_DATE, AMOUNT, PRICE, IMAGE,Company,Customer,Coupon

}
